package javax.bluetooth;

import java.io.IOException;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;

/**
 * Full implementation of ServiceRecord for emulation.
 */
public class ServiceRecordImpl implements ServiceRecord {

    private RemoteDevice hostDevice;
    private final Hashtable<Integer, DataElement> attributes = new Hashtable<>();
    private int handle = -1;
    private int deviceServiceClasses = 0;

    // Emulation extension
    private String connectionUrl;
    private String protocol; // btspp, btl2cap, btgoep
    private String uuid;
    private String serviceName;
    private int tcpPort;

    public ServiceRecordImpl(RemoteDevice hostDevice) {
        this.hostDevice = hostDevice;
    }

    // --- Emulation setters ---

    /**
     * Assigns the service-record handle generated by the local SDP registry.
     * This is an internal operation: applications must not modify attribute
     * 0x0000 through {@link #setAttributeValue(int, DataElement)}.
     */
    public void setHandle(int handle) {
        this.handle = handle;
        // SDP service-record handles are unsigned 32-bit values. The Java
        // transport represents them as an int, so preserve all 32 bits.
        attributes.put(Integer.valueOf(0x0000),
                new DataElement(DataElement.U_INT_4, ((long) handle) & 0xFFFFFFFFL));
    }

    public int getHandle() {
        return handle;
    }

    public void setConnectionUrl(String url) {
        this.connectionUrl = url;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getUuid() {
        return uuid;
    }

    public void setServiceName(String name) {
        this.serviceName = name;
    }

    public String getServiceName() {
        return serviceName;
    }

    public void setTcpPort(int port) {
        this.tcpPort = port;
    }

    public int getTcpPort() {
        return tcpPort;
    }

    // --- ServiceRecord interface ---

    @Override
    public DataElement getAttributeValue(int attrID) {
        return attributes.get(Integer.valueOf(attrID));
    }

    @Override
    public RemoteDevice getHostDevice() {
        return hostDevice;
    }

    @Override
    public int[] getAttributeIDs() {
        synchronized (attributes) {
            int[] ids = new int[attributes.size()];
            int i = 0;
            Enumeration<Integer> e = attributes.keys();
            while (e.hasMoreElements()) {
                ids[i++] = e.nextElement().intValue();
            }
            return ids;
        }
    }

    @Override
    public boolean populateRecord(int[] attrIDs) throws IOException {
        if (attrIDs == null) throw new NullPointerException();
        // In emulation, if host is remote, we would fetch from remote SDP.
        // For now, if we already have attributes, return true.
        // If host is remote and we have no attributes, try to query?
        // Simplified: return true if we have at least one requested attr, else false.
        if (hostDevice == null) {
            // Local record - all attributes already present
            return true;
        }
        // For remote, we already populated during discovery, so return true
        for (int id : attrIDs) {
            if (!attributes.containsKey(Integer.valueOf(id))) {
                // Attribute not present, but we could try to fetch
                // For emulation, return false if any missing?
                // Spec says populateRecord retrieves values, returns true if any value retrieved?
                // We'll return true if at least one exists, else false.
            }
        }
        return true;
    }

    @Override
    public String getConnectionURL(int requiredSecurity, boolean mustBeMaster) {
        if (connectionUrl == null) {
            // Generate from protocol and uuid if not set
            String base = protocol != null ? protocol : "btspp";
            String host = hostDevice != null ? hostDevice.getBluetoothAddress() : "localhost";
            String ch = uuid != null ? uuid : "1101";
            StringBuilder sb = new StringBuilder();
            sb.append(base).append("://").append(host).append(":").append(ch);
            if (serviceName != null) sb.append(";name=").append(serviceName);
            // Security params
            if (requiredSecurity == AUTHENTICATE_NOENCRYPT) {
                sb.append(";authenticate=true;encrypt=false");
            } else if (requiredSecurity == AUTHENTICATE_ENCRYPT) {
                sb.append(";authenticate=true;encrypt=true");
            }
            if (mustBeMaster) sb.append(";master=true");
            return sb.toString();
        }

        // Append security params if needed
        String url = connectionUrl;
        StringBuilder sb = new StringBuilder(url);
        if (requiredSecurity == AUTHENTICATE_NOENCRYPT) {
            if (!url.contains("authenticate")) sb.append(";authenticate=true;encrypt=false");
        } else if (requiredSecurity == AUTHENTICATE_ENCRYPT) {
            if (!url.contains("authenticate")) sb.append(";authenticate=true;encrypt=true");
        }
        if (mustBeMaster && !url.contains("master")) {
            sb.append(";master=true");
        }
        return sb.toString();
    }

    @Override
    public void setDeviceServiceClasses(int classes) {
        this.deviceServiceClasses = classes;
    }

    public int getDeviceServiceClasses() {
        return deviceServiceClasses;
    }

    @Override
    public boolean setAttributeValue(int attrID, DataElement attrValue) {
        // Handle reserved IDs
        if (attrID >= 0 && attrID <= 0x0008) {
            // Some IDs are not allowed to be modified per spec? But we allow for emulation
            // Spec says ServiceRecordHandle (0x0000) cannot be changed
            if (attrID == 0x0000) return false;
        }
        if (attrValue == null) {
            attributes.remove(Integer.valueOf(attrID));
        } else {
            attributes.put(Integer.valueOf(attrID), attrValue);
        }
        return true;
    }

    @Override
    public String toString() {
        return "ServiceRecord[handle=" + handle + " uuid=" + uuid + " name=" + serviceName + " url=" + connectionUrl + "]";
    }
}
